spring:
  datasource:
    url: jdbc:h2:mem:DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data.rest.detection-strategy: visibility
  flyway:
    enabled: false

atomist:
  keyValuePairUrl: "http://localhost:1234/KeyValuePair"
  teamDevOpsDetailsUrl: "http://localhost:1234/TeamDevOpsDetails"
  projectCreatedEventUrl: "http://localhost:1234/ProjectCreatedEvent"
  projectEnvironmentsRequestedEventUrl: "http://localhost:1234/ProjectEnvironmentsRequestedEvent"
  projectJenkinsJobRequestedEventUrl: "http://localhost:1234/ProjectJenkinsJobRequestedEvent"
  teamsLinkedToProjectEventUrl: "http://localhost:1234/TeamsLinkedToProjectEvent"
  slackIdentityUrl: "http://localhost:1234/SlackIdentity"
  deploymentEnvironmentUrl: "http://localhost:1234/DeploymentEnvironment"
  deploymentPipelineUrl: "http://localhost:1234/DeploymentPipeline"
  projectUrl: "http://localhost:1234/Project"
  projectBaseUrl: "http://localhost:1234/ProjectBase"
  bitbucketProjectUrl: "http://localhost:1234/BitbucketProject"
  gluonTeamUrl: "http://localhost:1234/GluonTeam"
  actionedByUrl: "http://localhost:1234/ActionedBy"
  gluonTenantUrl: "http://localhost:1234/GluonTenant"
  gluonTenantIdUrl: "http://localhost:1234/GluonTenantId"
  bitbucketRepositoryUrl: "http://localhost:1234/BitbucketRepository"
  devOpsEnvironmentDetailsUrl: "http://localhost:1234/DevOpsEnvironmentDetails"
  gluonApplicationUrl: "http://localhost:1234/GluonApplication"
  applicationProdRequestedEventUrl: "http://localhost:1234/ApplicationProdRequestedEvent"
  teamMemberCreatedEventUrl: "http://localhost:1234/TeamMemberCreatedEvent"
  applicationCreatedEventUrl: "http://localhost:1234/ApplicationCreatedEvent"
  packageConfiguredEventUrl: "http://localhost:1234/PackageConfiguredEvent"
  genericProdRequestedEventUrl: "http://localhost:1234/GenericProdRequestedEvent"
  teamCreatedEventUrl: "http://localhost:1234/TeamCreatedEvent"
  devOpsEnvironmentRequestedEventUrl: "http://localhost:1234/DevOpsEnvironmentRequestedEvent"
  devOpsEnvironmentProvisionedEventUrl: "http://localhost:1234/DevOpsEnvironmentProvisionedEvent"
  teamOpenShiftCloudMigratedEventUrl: "http://localhost:1234/TeamOpenShiftCloudMigratedEvent"
  membershipRequestCreatedEventUrl: "http://localhost:1234/MembershipRequestCreatedEvent"
  membersAddedToTeamEventUrl: "http://localhost:1234/MembersAddedToTeamEvent"
  memberRemovedFromTeamEventUrl: "http://localhost:1234/MemberRemovedFromTeamEvent"
  bitbucketProjectAddedEventUrl: "http://localhost:1234/BitbucketProjectAddedEvent"
  projectProductionEnvironmentsRequestedEventUrl: "http://localhost:1234/ProjectProductionEnvironmentsRequestedEvent"
  projectProductionEnvironmentsRequestClosedEventUrl: "http://localhost:1234/ProjectProductionEnvironmentsRequestClosedEvent"
  packageConfigurationRequestedEventUrl: "http://localhost:1234/PackageConfigurationRequestedEvent"
  configServerRequestedEventUrl: "http://localhost:1234/ConfigServerRequestedEvent"
  broadcastMessageAllChannelsEventUrl: "http://localhost:1234/BroadcastMessageAllChannelsEvent"
  teamSlackChannelCreatedEventUrl: "http://localhost:1234/TeamSlackChannelCreatedEvent"
