spring:
  datasource:
    url: jdbc:h2:./testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  data.rest.detection-strategy: visibility
  flyway:
    enabled: true
gluon:
  encryption:
    encryptionKey: "REPLACE_THIS"
  project:
    defaultProdApprovals: 3